### ISSUE TITLE
Webrtc Exception: RTP header size insufficient

### ISSUE THREAD

**Issue by MSchif** [GRVYDEV/Project-Lightspeed#1]
Windows 10: When pressing "Start Streaming" in OBS the Lightspeed-webrtc crashes with the following exception:

`$ lightspeed-webrtc.exe --addr=localhost`
`Waiting for RTP Packets`
`panic: size 12 < 16: RTP header size insufficient`
`goroutine 1 [running]:`
`main.main()`
`        C:/Users/User/go/pkg/mod/github.com/!g!r!v!y!d!e!v/lightspeed-webrtc@v0.0.0-20210104031427-e868038a7eba/main.go:103 +0x867`

Followed the instructions for installation and usage (ingest, webrtc and react running). IP adress 'localhost' in 'services.json' and as '--addr' parameter of webrtc. OBS->Settings->Stream->Service "Project Lightspeed' like seen in the screenshot. Ingest seems to be working and prints:

`Listening on port 8084`
`Hashes match!`
`Client connected!`
`Protocol Version: 0.9`
`Vendor Name: OBS Studio`
`Vendor Version: 25.0.4`
`Video Codec: H264`
`Video Height: 720`
`Video Width: 1280`
`Audio Codec: OPUS`

![grafik](https://user-images.githubusercontent.com/17830502/103521817-aae3d780-4e79-11eb-8796-128cfa72bdce.png)

**Comment by GRVYDEV** [comment]
Hmmm this is very interesting. I have not tested hosting the servers on Windows at all so give me a little while to dig into this one!

**Comment by Zibbp** [comment]
Having the same error running on Ubuntu 20. Instantly errors when starting a stream.

**Comment by GRVYDEV** [comment]
> Having the same error running on Ubuntu 20. Instantly errors when starting a stream.

Are you using localhost or a remote Ubuntu server?

**Comment by GRVYDEV** [comment]
Checkout this branch and let me know if this solves it https://github.com/GRVYDEV/Lightspeed-webrtc/tree/rtp-error-patch

**Comment by watate** [comment]
Hi, I have the same issue but I'm running on WSL.

Still same error after checking out rtp-error-patch but instead of printing once it prints continuously.

![image](https://user-images.githubusercontent.com/40448679/103559593-58de9880-4ef1-11eb-8069-f0a03f1afc4d.png)

**Comment by GRVYDEV** [comment]
> Hi, I have the same issue but I'm running on WSL.
> 
> Still same error after checking out rtp-error-patch but instead of printing once it prints continuously.
> 
> ![image](https://user-images.githubusercontent.com/40448679/103559593-58de9880-4ef1-11eb-8069-f0a03f1afc4d.png)

hm could you go into more detail about your configuration

**Comment by karoldrazek** [comment]
Running lightspeed services on Ubuntu 20 LTS and OBS on Windows. Just tested 'rtp-error-patch' same error.

Configuration:
```
Hashes match!
Client connected!
Protocol Version: 0.9
Vendor Name: OBS Studio
Vendor Version: 24.0.0
Video Codec: H264
Video Height: 720
Video Width: 1280
Audio Codec: OPUS
```

![image](https://user-images.githubusercontent.com/9444742/103560293-d4bbef00-4eb7-11eb-803d-6fe128207ddb.png)

**Comment by watate** [comment]
![image](https://user-images.githubusercontent.com/40448679/103560232-621c3500-4ef2-11eb-9e2a-14eac46c0737.png)



> 
> 
> > Hi, I have the same issue but I'm running on WSL.
> > Still same error after checking out rtp-error-patch but instead of printing once it prints continuously.
> > ![image](https://user-images.githubusercontent.com/40448679/103559593-58de9880-4ef1-11eb-8069-f0a03f1afc4d.png)
> 
> hm could you go into more detail about your configuration

![image](https://user-images.githubusercontent.com/40448679/103560306-84ae4e00-4ef2-11eb-933f-461e86c5318d.png)

I followed the readme for the setup. Running lightspeed on Ubuntu (WSL) and OBS on Windows

**Comment by GRVYDEV** [comment]
> ![image](https://user-images.githubusercontent.com/40448679/103560232-621c3500-4ef2-11eb-9e2a-14eac46c0737.png)
> 
> > > Hi, I have the same issue but I'm running on WSL.
> > > Still same error after checking out rtp-error-patch but instead of printing once it prints continuously.
> > > ![image](https://user-images.githubusercontent.com/40448679/103559593-58de9880-4ef1-11eb-8069-f0a03f1afc4d.png)
> > 
> > 
> > hm could you go into more detail about your configuration
> 
> ![image](https://user-images.githubusercontent.com/40448679/103560306-84ae4e00-4ef2-11eb-933f-461e86c5318d.png)
> 
> I followed the readme for the setup.

Hm this seems to be a windows OBS issue

**Comment by GRVYDEV** [comment]
What version of OBS are you using

**Comment by karoldrazek** [comment]
OBS 24.0.0 and 26.1.0 (issue appears on both)

**Comment by GRVYDEV** [comment]
> 
> 
> OBS 24.0.0 and 26.1.0 (issue appears on both)

Well I have some good news! Its a phantom error. Well not exactly. Basically it is an error that doesnt break anything. I am currently streaming from windows and I am able to watch it back just fine however it is spamming me with those error messages. For now I will change it to do nothing if it cannot unmarshal a packet. For proof it works go to http://stream.gud.software
