### ISSUE TITLE
Feedback on the setup

### ISSUE THREAD

**Issue by paulirish** [GRVYDEV/Project-Lightspeed#10]
I wanted to get this running locally for fun. Had a few snafus so just providing feedback to perhaps help the readme's. (Unfortunately I don't have the time to make the changes myself.)

* meta: Getting everything up and running on localhost/127.0.0.1 seems like the first step, so perhaps all the docs/defaults should start you there, before you deploy things
* the ws port is hardcoded, but I didn't expect that. Might as well add some comments in wsUrl.js to indicate that 8080 is hardcoded as the ws port in ls-webrtc
* in the services.json i tried `http://localhost` and `http://localhost:8084` and `rtmp://127.0.0.1` and none worked. finally just tried `127.0.0.1` and it worked. your docs kinda suggest "just" the IP but since it was different then the rest of the server urls in services.json i wasn't sure.  also i was surprised there was no port indicated here.
* in my already locally installed version of `serve` (6.4.9) the port flag is is `-p` not `-l`. shrug.
* i still don't really understand how the injest server communicates with lightspeed-webrtc (is it the 65534 port i saw in the source?).. but tbh a user probably doesn't need to understand this bit 😛 
. It just stood out since I was manually matching up IPs and ports across the other parts, and this one seemed to work automagically.
   * can ls-webrtc output a log entry when it is 'connected' to the injest server? would be nice just to confirm that bit is working.
* the "View demo" link in all 4 readmes don't point to what i expected. :)  in -injest, it just points to the root of -injest. even the project-ls readme it just points to itself. I wouldn't really call that a "demo", more just the "Project Overview" perhaps.. or "overview documentation". but i certainly preferred using the aggregated docs instead of visiting each. ;)

anyway..

<details>
<summary>nice job on all this. it was fun to get going. :)</summary>

![Screen Shot 2021-01-04 at 3 55 21 PM](https://user-images.githubusercontent.com/39191/103591561-5d7d5f80-4ea5-11eb-9ae1-257191e8a3ca.jpg)

</details>

**Comment by GRVYDEV** [comment]
Hi Paul thank you for writing this! I will definitely go through the docs and clear up all of the points you mention here! I’m glad you got it to work and hope you stick around to watch it evolve :)

**Comment by GRVYDEV** [comment]
In regards to the project demo link I used a Readme template and have not setup a demo yet so I will absolutely being doing that in the future!

**Comment by GRVYDEV** [comment]
Just gave the README a refresh taking this into account! If anything is still unclear please reopen this issue!
