### ISSUE TITLE
Listening to port 8084

### ISSUE THREAD

**Issue by HerrTaschenbier98** [GRVYDEV/Project-Lightspeed#13]
Hey there,
first of all, thank you for posting this project.
When I am starting the "cargo run --release" command my terminal stucks at the Message "Listening on port 8084". Is it a Network Problem or am I the Problem.

**Comment by GRVYDEV** [comment]
It will stick at "Listening on port 8084" until you connect to it with OBS

**Comment by GRVYDEV** [comment]
> Hey there,
> first of all, thank you for posting this project.
> When I am starting the "cargo run --release" command my terminal stucks at the Message "Listening on port 8084". Is it a Network Problem or am I the Problem.

Your terminal "sticking" means that the ingest service is listening on port 8084 and waiting for a connection to come in

**Comment by HerrTaschenbier98** [comment]
So do I have to execute it in Background?
Thanks for your reply, I appriciate your effor.

**Comment by GRVYDEV** [comment]
> So do I have to execute it in Background?
> Thanks for your reply, I appriciate your effor.

You could if you wanted to! Right now what I do is run each of the applications in a different terminal window however we will be adding docker support very soon which means all 3 apps will be easily run in the same window

**Comment by torchsmith** [comment]
I use 

> So do I have to execute it in Background?
> Thanks for your reply, I appriciate your effor.

Assuming you are running this on linux, I use the handy `screen` command to run all my stuff simultaneously on my server without needing to have any terminal window open!

I can setup my 2 "screens", one for WebRTC, and one for Ingest, and then I can close my ssh session and it will stay running.

**Comment by HerrTaschenbier98** [comment]
> I use
> 
> > So do I have to execute it in Background?
> > Thanks for your reply, I appriciate your effor.
> 
> Assuming you are running this on linux, I use the handy `screen` command to run all my stuff simultaneously on my server without needing to have any terminal window open!
> 
> I can setup my 2 "screens", one for WebRTC, and one for Ingest, and then I can close my ssh session and it will stay running.

Thank you! Never used screen bevore, it is great to know such a tool.
