### ISSUE TITLE
Info: You get some attention from public news website

### ISSUE THREAD

**Issue by Jonn3y** [GRVYDEV/Project-Lightspeed#21]
Just want to let you know that one of the biggest tech news websites in Germany wrote a small article about your project
https://www.heise.de/news/Lightspeed-Neue-Open-Source-Software-fuers-Live-Streaming-Komplettpaket-5005002.html

**Comment by GRVYDEV** [comment]
Okay now this is awesome!

**Comment by GRVYDEV** [comment]
Closing this but thank you for letting me know!
