### ISSUE TITLE
Info: Discord Server is now LIVE! Demo video is also now LIVE!

### ISSUE THREAD

**Issue by GRVYDEV** [GRVYDEV/Project-Lightspeed#22]
Hey guys!
I went ahead and made a Discord server so we have a better place for bug fixing and technical support. I will be looking for some moderators so if you are interested feel free to join and message me! Also if you are having any trouble please join the server and I will do my best to help you work through it!

Edit: I also finally made a demo video! The demo link now works on all 4 repositories!

Edit Edit: I uploaded the wrong video so right now there is no sound. New one is uploading right now!

[Server](https://discord.gg/UpQZANPYmZ)

**Comment by Jonn3y** [comment]
I think you should add this to the readme at some point!

**Comment by GRVYDEV** [comment]
> I think you should add this to the readme at some point!

There is a badge for it but I will add a dedicated section!

**Comment by GRVYDEV** [comment]
> I think you should add this to the readme at some point!

Done :)

**Comment by GRVYDEV** [comment]
This is no longer new so closing
