### ISSUE TITLE
Request: Diagram of how each component interacts with the other

### ISSUE THREAD

**Issue by armlesshobo** [GRVYDEV/Project-Lightspeed#23]
If you're like me and have a very basic understanding of OBS, FTL, WebRTC, etc, it would be very helpful to see how each Lightspeed component interacts with the other.

From what I could gather, the diagram looks something roughly like this:    OBS <--> Ingest <--> WebRTC <---> React client

If not, then that should illustrate the need for a diagram :D

**Comment by GRVYDEV** [comment]
I will work on this right now!

**Comment by armlesshobo** [comment]
Thank you! <3
