### ISSUE TITLE
Lightspeed-React issues

### ISSUE THREAD

**Issue by acidrs03** [GRVYDEV/Project-Lightspeed#28]
Hello,
         I have managed to follow everything in the installation guide and have Lightspeed-ingest working and i think Lightspeed-webRTC.
However after serving Lightspeed-React i cannot connect to the page and just get a "This Page cannot be reached" message.
I have changed the config.json wsURL to ws://10.0.0.36:8080/websocket and have opened ports on ufw . However from another machine it will not display the site. 
If i add the port 8443 onto the end then sometimes it does load a blank dark grey site but nothing appears on it.  
Can someone help with getting this working.

I am running Lightspeed-React on a Ubuntu 20.04 machine and running OBS and trying to access the site on a windows 10 machine.

**Comment by GRVYDEV** [comment]
Hi! You cannot use the internal IP for the websocket address it needs to be the external IP of the machine. Also make sure you are serving the build folder of the react app using `serve -s build -l 80` after running `npm run build`

**Comment by acidrs03** [comment]
Thanks for the response. 
I changed the IP in `config.json` to my external ip and rebuilt running `npm run build` with no luck on loading the react site. 
I checked the ports on UFW and can see that they are all open 80, 443, 8080, 8084. 
When i start streaming on OBS i get a "Client Connected" message in Lightspeed-ingest so at least that port is working.

Running `sudo lsof -i -P -n | grep LISTEN`  i see
```
lightspee 3558          acidrs    9u  IPv4  66580      0t0  TCP *:8084 (LISTEN)
lightspee 3568          acidrs    7u  IPv6  62919      0t0  TCP *:8080 (LISTEN)
sshd      3776          acidrs   10u  IPv6  66991      0t0  TCP [::1]:6010 (LISTEN)
sshd      3776          acidrs   11u  IPv4  66992      0t0  TCP 127.0.0.1:6010 (LISTEN)
serve     4263          acidrs    3u  IPv6  69496      0t0  TCP *:8443 (LISTEN)
```
So from what i can tell serve isnt listening on port 80? even though im running `serve -s build -l 80`

**Comment by GRVYDEV** [comment]
If you cant see the react site at all that means there is something going on with your network config. Regardless of the websocket working you should be able to see the react site if you're serving it on port 80

**Comment by Buttabert** [comment]
Hi,
I played around with it for some hours now and here are some findings and thoughts from my side:
`npm run build` resets your `config.json` and you always have to set it again afterwards (or you edit the corresponding file in the public folder). The install instructions are either the wrong way or mention the wrong file.

What extremely helped is using the browser console to see the error. For example just opening the ports 8048, 8080 and 80 wasn't enough. I tried opening 65535 too since that can be seen using `ss` (see the mentioned bug in the readme) but it still wasn't enough but my browser console complained about some ports not being reachable suddenly... so I disabled ufw for now and it worked fine. I would have to investigate that further.

I'm also running `serve` on a different port so that it doesn't need root privileges but that probably won't change anything.

The software itself is really nice though. Exactly 1s of latency across the country and it's perfect to have some kind of private stream for your friends. Runs flawlessly on 1 vCore and 512MB RAM, just the compiling steps take a while.

**Comment by acidrs03** [comment]
Ok so i did a little more testing to see if i can find out why i couldn't access the react site. Eventually found that i couldnt bind to port 80 due to a permission error. Running `sudo serve -p 80 -s build` however returned `. can't be served because it's not readable: open .: permission denied` . 
I ended up messing with it some more and found i had some node , go and rust issues due to installation. Ended up having to reinstall the OS. 
So after OS reinstall i went through the guide step by step and everything looked good, up until the point i get to the `serve` part of the Lightspeed-react section.
When i run `serve -p 80 -s build` i get `listen tcp 0.0.0.0:80: bind: permission denied`
When i run `sudo serve -p 80 -s build` i get  `. can't be served because it's not readable: open .: permission denied`

If i change the port to say 1234 then it runs. However connecting from either publicIP:1234 or 10.0.0.36:1234 both give a message in the console 
`http: TLS handshake error from publicIP:59556: tls: first record does not look like a TLS handshake`
This is the same happens using localIP:1234 . 
i also tried connecting to the site from my cell phone, not connected via wifi but instead using mobile data. Same TLS error message. 
Has anyone else had issues trying to run from port 80 or had issues with TLS handshakes?


Update: I have managed to get the react site loaded by changing the serve command slightly. Running `serve -p 1234 build` without the -s flag works.

**Comment by GRVYDEV** [comment]
> Hi,
> I played around with it for some hours now and here are some findings and thoughts from my side:
> `npm run build` resets your `config.json` and you always have to set it again afterwards (or you edit the corresponding file in the public folder). The install instructions are either the wrong way or mention the wrong file.
> 
> What extremely helped is using the browser console to see the error. For example just opening the ports 8048, 8080 and 80 wasn't enough. I tried opening 65535 too since that can be seen using `ss` (see the mentioned bug in the readme) but it still wasn't enough but my browser console complained about some ports not being reachable suddenly... so I disabled ufw for now and it worked fine. I would have to investigate that further.
> 
> I'm also running `serve` on a different port so that it doesn't need root privileges but that probably won't change anything.
> 
> The software itself is really nice though. Exactly 1s of latency across the country and it's perfect to have some kind of private stream for your friends. Runs flawlessly on 1 vCore and 512MB RAM, just the compiling steps take a while.

Hi! So we also need to open ports 20000-20500 for the WebRTC service! Let me know if opening solves your issue!

**Comment by GRVYDEV** [comment]
> Ok so i did a little more testing to see if i can find out why i couldn't access the react site. Eventually found that i couldnt bind to port 80 due to a permission error. Running `sudo serve -p 80 -s build` however returned `. can't be served because it's not readable: open .: permission denied` .
> I ended up messing with it some more and found i had some node , go and rust issues due to installation. Ended up having to reinstall the OS.
> So after OS reinstall i went through the guide step by step and everything looked good, up until the point i get to the `serve` part of the Lightspeed-react section.
> When i run `serve -p 80 -s build` i get `listen tcp 0.0.0.0:80: bind: permission denied`
> When i run `sudo serve -p 80 -s build` i get `. can't be served because it's not readable: open .: permission denied`
> 
> If i change the port to say 1234 then it runs. However connecting from either publicIP:1234 or 10.0.0.36:1234 both give a message in the console
> `http: TLS handshake error from publicIP:59556: tls: first record does not look like a TLS handshake`
> This is the same happens using localIP:1234 .
> i also tried connecting to the site from my cell phone, not connected via wifi but instead using mobile data. Same TLS error message.
> Has anyone else had issues trying to run from port 80 or had issues with TLS handshakes?
> 
> Update: I have managed to get the react site loaded by changing the serve command slightly. Running `serve -p 1234 build` without the -s flag works.

Awesome! Im not sure why -s would cause a problem but I am glad you have solved it! Can we close this issue or would you like some more help?

**Comment by acidrs03** [comment]
> > Ok so i did a little more testing to see if i can find out why i couldn't access the react site. Eventually found that i couldnt bind to port 80 due to a permission error. Running `sudo serve -p 80 -s build` however returned `. can't be served because it's not readable: open .: permission denied` .
> > I ended up messing with it some more and found i had some node , go and rust issues due to installation. Ended up having to reinstall the OS.
> > So after OS reinstall i went through the guide step by step and everything looked good, up until the point i get to the `serve` part of the Lightspeed-react section.
> > When i run `serve -p 80 -s build` i get `listen tcp 0.0.0.0:80: bind: permission denied`
> > When i run `sudo serve -p 80 -s build` i get `. can't be served because it's not readable: open .: permission denied`
> > If i change the port to say 1234 then it runs. However connecting from either publicIP:1234 or 10.0.0.36:1234 both give a message in the console
> > `http: TLS handshake error from publicIP:59556: tls: first record does not look like a TLS handshake`
> > This is the same happens using localIP:1234 .
> > i also tried connecting to the site from my cell phone, not connected via wifi but instead using mobile data. Same TLS error message.
> > Has anyone else had issues trying to run from port 80 or had issues with TLS handshakes?
> > Update: I have managed to get the react site loaded by changing the serve command slightly. Running `serve -p 1234 build` without the -s flag works.
> 
> Awesome! Im not sure why -s would cause a problem but I am glad you have solved it! Can we close this issue or would you like some more help?

@GRVYDEV Yeah we can close this issue. Im sure my issues are just due to my home development environment, as others haven't had the same issues.

**Comment by GRVYDEV** [comment]
Closed
