### ISSUE TITLE
any way to password protect the stream website?

### ISSUE THREAD

**Issue by tommy1735** [GRVYDEV/Project-Lightspeed#47]
any way to password protect the stream website ?

**Comment by Lunaphied** [comment]
You can combine something like https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/ with TLS support in Nginx to have secure authentication. 

You can see in this script https://github.com/GRVYDEV/Project-Lightspeed/blob/main/contrib/ubuntu_installer/ubuntu_installer.sh an example of how Nginx should be configured to act as an intermediary.

**Comment by GRVYDEV** [comment]
Closing this since it is out of scope of this project directly
